stages:
  - build

build-linux64:
  image: ubuntu:latest
  stage: build
  cache:
    key:
      prefix: build-linux64
      files: ["CMakeLists.txt", "build-cross/build-linux64.sh"]
    paths:
      - build-cross/build-linux64
  script:
    - apt-get update
    - apt-get install -y build-essential cmake git libgl-dev libglu1-mesa-dev libxi-dev libglm-dev
    - pushd build-cross
    - ./build-linux64.sh
    - popd
    - mv build-cross/install-linux64/ install-linux64-x86_64-$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-linux64-*/bin/
      - install-linux64-*/lib/
      - install-linux64-*/share/
    expire_in: 1 week

build-linux32:
  image: ubuntu:latest
  stage: build
  cache:
    key:
      prefix: build-linux32
      files: ["CMakeLists.txt", "build-cross/build-linux32.sh"]
    paths:
      - build-cross/build-linux32
  script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install -y g++-i686-linux-gnu make cmake git libgl-dev:i386 libglu1-mesa-dev:i386 libxi-dev:i386 libglm-dev
    - pushd build-cross
    - ./build-linux32.sh
    - popd
    - mv build-cross/install-linux32/ install-linux32-i686-$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-linux32-*/bin/
      - install-linux32-*/lib/
      - install-linux32-*/share/
    expire_in: 1 week

build-mingw64:
  image: ubuntu:latest
  stage: build
  cache:
    key:
      prefix: build-mingw64
      files: ["CMakeLists.txt", "build-cross/build-mingw64.sh"]
    paths:
      - build-cross/build-mingw64
  script:
    - apt-get update
    - apt-get install -y mingw-w64 make cmake git
    - pushd build-cross
    - ./build-mingw64.sh
    - popd
    - mv build-cross/install-mingw64/ install-mingw64-x86_64-$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-mingw64-*/bin/
      - install-mingw64-*/share/
    expire_in: 1 week

build-mingw32:
  image: ubuntu:latest
  stage: build
  cache:
    key:
      prefix: build-mingw32
      files: ["CMakeLists.txt", "build-cross/build-mingw32.sh"]
    paths:
      - build-cross/build-mingw32
  script:
    - apt-get update
    - apt-get install -y mingw-w64 make cmake git
    - pushd build-cross
    - ./build-mingw32.sh
    - popd
    - mv build-cross/install-mingw32/ install-mingw32-i686-$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-mingw32-*/bin/
      - install-mingw32-*/share/
    expire_in: 1 week
