stages:
  - build

build-linux:
  image: ubuntu:latest
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential cmake git libgl-dev libglew-dev freeglut3-dev libglm-dev graphicsmagick-libmagick-dev-compat libstb-dev
    - ./build.sh
    - mv install/ install-linux-$(uname -m)_$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-linux-*/

build-mingw64:
  image: ubuntu:latest
  stage: build
  script:
    - apt-get update
    - apt-get install -y mingw-w64 make cmake git
    - pushd build-cross
    - ./build-mingw64.sh
    - popd
    - mv build-cross/install-mingw64/ install-mingw64-x86_64-$(git rev-parse --short HEAD)/
  artifacts:
    paths:
      - install-mingw64-*/
