#include "GLImage.h"

#include <opencv2/opencv.hpp>

using namespace std;

// Generated by ChatGPT.
void GLImage::Save(const fs::path &path) const
{
  cv::Mat img(height, width, (type == GLImageType::RGBA ? CV_8UC4 : CV_8UC3), const_cast<byte *>(data.data()));
  if(type == GLImageType::RGB) {
    cv::cvtColor(img, img, cv::COLOR_RGB2BGR);
  } else {
    cv::cvtColor(img, img, cv::COLOR_RGBA2BGRA);
  }
  cv::flip(img, img, 0);
  cv::imwrite(path.string(), img);
}

// Generated by ChatGPT.
void GLImage::Load(const fs::path &path)
{
  cv::Mat img = cv::imread(path.string(), cv::IMREAD_UNCHANGED);
  if(img.channels() == 3) {
    cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
  } else if(img.channels() == 4) {
    cv::cvtColor(img, img, cv::COLOR_BGRA2RGBA);
  }
  cv::flip(img, img, 0);
  width = img.cols;
  height = img.rows;
  type = (img.channels() == 4) ? GLImageType::RGBA : GLImageType::RGB;
  data.assign((byte *)img.data, (byte *)img.data + img.total() * img.elemSize());
}
