// Implement macOS window maximization using Cocoa
// Generated by: Copilot <223556219+Copilot@users.noreply.github.com>

#import "GLApplication.h"
#import "Utils.h"

#ifdef __APPLE__
#import <Cocoa/Cocoa.h>
#ifdef FREEGLUT
#include <GL/freeglut_ext.h>
#endif

#include <iostream>

using namespace std;

void GLApplication::MaximizeWindow() const
{
  @autoreleasepool {
    // Prefer native window pointer from freeglut (if available)
#ifdef FREEGLUT
    void *wnd = glutGetWindowData();
    if(wnd) {
      NSWindow *win = (NSWindow *)wnd;
      if(win) {
        NSScreen *screen = [win screen];
        if(!screen) screen = [NSScreen mainScreen];
        if(screen) {
          NSRect frame = [screen visibleFrame];
          if([NSThread isMainThread]) {
            [win setFrame:frame display:YES animate:YES];
          } else {
            dispatch_async(dispatch_get_main_queue(), ^{ [win setFrame:frame display:YES animate:YES]; });
          }
          return;
        }
      }
    }
#endif

    // Fallback to keyWindow
    NSWindow *target = [NSApp keyWindow];
    if(!target) {
      for(NSWindow *w in [NSApp windows]) {
        if(w && [w isVisible]) {
          target = w;
          break;
        }
      }
    }
    if(!target) {
      cerr << "Warning: GLApplication::MaximizeWindow(): could not find Cocoa window." << endl;
      return;
    }

    NSScreen *screen = [target screen];
    if(!screen) screen = [NSScreen mainScreen];
    if(!screen) {
      cerr << "Warning: GLApplication::MaximizeWindow(): could not find NSScreen." << endl;
      return;
    }

    NSRect frame = [screen visibleFrame];
    if([NSThread isMainThread]) {
      [target setFrame:frame display:YES animate:YES];
    } else {
      dispatch_async(dispatch_get_main_queue(), ^{ [target setFrame:frame display:YES animate:YES]; });
    }
  }
}

#endif  // __APPLE__
